### PR TITLE
Upkeep

### PR DESCRIPTION
**Pull request by dunkenwg**

### CODE REVIEW

**Comment by dunkenwg** [comment]
resolves #infrastructure-issues#204

**Comment by dunkenwg** [comment]
One test in `test-knit.R` is failing with the following error: `'\U' used without hex digits in character string (<text>:3:13)`.

I'm guessing that this has to do with file path convention differences between operating systems. Both mac and ubuntu accept `\`, but windows uses `\\` (the first `\` is an escape character for the second `\`). Should we skip this test on windows or remove the windows R-CMD-check or something else?

**Comment by aylapear** [comment]
> One test in `test-knit.R` is failing with the following error: `'\U' used without hex digits in character string (<text>:3:13)`.
> 
> I'm guessing this has to do with file path differences between operating systems. I think both mac and ubuntu accept `\`, but windows uses `\\` (the first `\` is an escape character for the second `\`). Should we skip this test on windows or remove the windows R-CMD-check?

It would be good to dig into the error further before turning the test off and seeing if there is a change we can make to the code so it works on both windows and other systems.  I think you should dig into the code and determine what exactly is causing the issue in windows and if anything can be done to fix it as it.

**Comment by dunkenwg** [comment]
I think the error is occurring because of this line in `knit.R`: `utils::browseURL(paste0('file://', path))`. I tried switching it to `utils::browseURL(paste0('file:///', path))` to see if that would fix the problem in windows. It didn't... Do either of you have any suggestions for making the url file path work for windows?

**Comment by aylapear** [comment]
> I think the error is occurring because of this line in `knit.R`: `utils::browseURL(paste0('file://', path))`. I tried switching it to `utils::browseURL(paste0('file:///', path))` to see if that would fix the problem in windows. It didn't... Do either of you have any suggestions for making the url file path work for windows?

Have you tried building the file path with the `file.path()` function and seen if this helps instead of using `paste0()`?

**Comment by dunkenwg** [comment]
The Windows R-CMD-check is actually failing on this line in `sbr_knit_results()`:
```
  path <- rmarkdown::render(
    input = input,
    output_format = "html_document",
    quiet = quiet
  )
```
I tried adding an argument for the output directory that would differ between systems:
```
  path <- rmarkdown::render(
    input = input,
    output_format = "html_document",
    output_dir = file.path(dirname(file)),
    quiet = quiet
  )
```
but we're still getting the file path error.

I could try making if/else statements to run different code on Windows, but I don't really know what else to change after scouring the internet on this error. We could also skip this test on Windows, but users likely wouldn't be able to use `sbr_knit_results()` on Windows. Thoughts?

**Comment by aylapear** [comment]
image

This is happening because of the path of the main variable in the "results.Rmd" document we are creating for the test. I tested it on a windows machine and if I switch the slashes to be `/` or to be `\\` then it works fine. I think based on how these files are normally set up then it is just how we are doing the testing and not applicable to how the function is normally used.

I think we can skip on windows but worth filing an issue on this as there may be a different way to set up the test to be more robust on all OS in the futre. I believe this function will work on windows machines.

**Comment by aylapear** [comment]
I was incorrect above, this issue is not just about how the test is set up but the purpose of this function which is to created a quick way to view the tables, plots, figures, etc in the report format but it is not actually generating the report we write up. 

To fix this we need to make sure it encodes it properly for windows where the "quick" report structure is created. In the `report-text.R` file try changing the `normalizePath(main)` to be `normalizePath(main, win slash = "/")` and see if this will now pass on windows machines and other OS.

**Comment by dunkenwg** [comment]
@aylapear, this fix worked! If I had to make an (educated) guess as to why `test-knit.R` is failing on windows when it calls `sbr_knit_results()`, I'd say it all starts with `writeLines(report_text(sub = sub, main = main), con = input)` on line 28 of `sbr_knit_results()`. This line first calls `report_text()` which writes a really long string. `writeLines()` then writes this string to `results.Rmd`. Without the `winslash` argument in line 11 of `report_text()` this file fails to render on windows when `rmarkdown::render()` is called on line 30 of `sbr_knit_results()`.

If I've got the fix correct, you can go ahead and merge the pull request as long as @joethorley is happy with the changes.

**Comment by dunkenwg** [comment]
@joethorley and @aylapear, can I go ahead and merge this pull request?

**Review by joethorley — CHANGES_REQUESTED** [review]
Looks good except I don't think the report.Rmd file should be kicking around at the top level of the directory or even in tests/testthat as well. Can you delete these files and then add to the .gitignore file.

**Comment by aylapear** [comment]
> @aylapear, this fix worked! If I had to make an (educated) guess as to why `test-knit.R` is failing on windows when it calls `sbr_knit_results()`, I'd say it all starts with `writeLines(report_text(sub = sub, main = main), con = input)` on line 28 of `sbr_knit_results()`. This line first calls `report_text()` which writes a really long string. `writeLines()` then writes this string to `results.Rmd`. Without the `winslash` argument in line 11 of `report_text()` this file fails to render on windows when `rmarkdown::render()` is called on line 30 of `sbr_knit_results()`.


Cool yes this sounds correct in terms of the flow. One more thing to to note is the `winslash` default argument is "\\" so what happens is the `writeLines` and `normalizePath` function combo the resulting file path only ends up with "\" (single slash) which can't be read on a windows system because windows machines can't interpret this. Switching it to "/" solves the problem for windows machines and doesn't affect or change how Mac or Linux paths are written.

**Comment by aylapear** [comment]
Once the next changes Joe requested are made I will review.

**Review by joethorley — APPROVED** [review]

**Comment by dunkenwg** [comment]
@aylapear, this should be ready for review now

**Review by aylapear — APPROVED** [review]
Looks good. Thanks for sticking with this one, I know it took a while to get done! 
Remember to bump the version and update the news during the merge process.

**Pull request merged**
